### ISSUE TITLE
Practica Architech

### ISSUE THREAD

**Issue by Sandra631** [SistemasTecTlaxiaco/practica-architect-Sandra631#1]
[Practica Architech.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-Sandra631/files/7166722/Practica.Architech.pdf)

**Comment by bg55-a** [comment]
reviso adolfo german vasquez rojas 
90 puntos --18%

**Comment by josealfredo79** [comment]
Faltaron las conclusiones..

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
